### ISSUE TITLE
[GD01] Nhận yêu cầu lần đầu từ khách hàng

### ISSUE THREAD

**Issue by ThongDB18110207** [TuongThongHCMUTE/ProjectSE_Nhom16_AppHocNgonNgu#1]
Input:  Yêu cầu về sản phẩm của khách hàng
Output:  Tài liệu đặc tả

**Comment by stark3105** [comment]
Tên đề tài: Xây dựng website học ngôn ngữ

**Comment by TuongLe18110234** [comment]
Yêu cầu từ khách hàng:
1 | Giao diện chuyên nghiệp
2 | Phân quyền tài khoản
3 | Đăng kí và đăng nhập tài khoản học viên
4 | Chức năng học thông qua các chủ đề
5 | Chức năng học thông qua video
6 | Chức năng học thông qua tin tức, các bài báo
7 | Chức năng trò chơi giúp ôn tập kiến thức
8 | Chức năng kiểm tra và đánh giá năng lực
9 | Chức năng nhắc nhở giờ học
10 | Chức năng ghi chú bằng flash card
11 | Xếp hạng học viên
12 | Diễn dàng trao đổi

**Comment by TuongLe18110234** [comment]
[ProjectSE_Nhan_yeu_cau_lan_dau_tu_khac_hang.docx](https://github.com/ThongDB18110207/ProjectSE_Nhom16_AppHocNgonNgu/files/6216794/ProjectSE_Nhan_yeu_cau_lan_dau_tu_khac_hang.docx)
