### ISSUE TITLE
Thiết kế giao diện trang đăng nhập, đăng ký, trang chủ

### ISSUE THREAD

**Issue by HungDo007** [TuongThongHCMUTE/ProjectSE_Nhom16_AppHocNgonNgu#17]

**Comment by TuongLe18110234** [comment]
https://github.com/TuongThongHCMUTE/ProjectSE_Nhom16_AppHocNgonNgu/tree/master/Languages_Learning_App

**Comment by TuongLe18110234** [comment]
Link demo: https://youtu.be/nVKYuWk7PII
