### ISSUE TITLE
Vẽ lược đồ trạng thái

### ISSUE THREAD

**Issue by ThongDB18110207** [TuongThongHCMUTE/ProjectSE_Nhom16_AppHocNgonNgu#19]
Nhóm sinh viên vẽ sơ đồ trạng thái cho các object đã thiết kế được của đề tài. Nhóm tạo milestone, issues trên github và gán thành viên thực hiện các lược đồ trạng thái tương ứng. Ví dụ về lượng đồ trạng thái đơn giản cho user:

Những yêu cầu cần có khi nộp bài:

- Nhóm tạo milestone trên github, trong milestones chứa issue Vẽ lược đồ trạng thái.

- File nộp bài là PDF, với cấu trúc file là : <GroupX>_Luocdotrangthai.pdf được bỏ vào thư mục document trong github(Nếu chưa có thể phải tạo để dễ quản lý, folder này có thể có tên là Docs, doc, document đều được, nhóm nào đã có rồi thì không cần tạo lại nữa). File sau khi hoàn thành và up lên github xong, thì vào issue comment tên file vào trong mục comment của issue. Close issue nếu đã xong task. 

- Đính kèm link milestones vào mục nộp bài.

**Comment by ThongDB18110207** [comment]
https://github.com/TuongThongHCMUTE/ProjectSE_Nhom16_AppHocNgonNgu/blob/master/document/Group16_Luocdotrangthai.pdf

**Comment by TuongLe18110234** [comment]
Tên tài liệu: Group16_Luocdotrangthai.pdf
