### ISSUE TITLE
Nộp file test case cho v1

### ISSUE THREAD

**Issue by ThongDB18110207** [TuongThongHCMUTE/ProjectSE_Nhom16_AppHocNgonNgu#23]
[Group16_TestCaseV1.0.xls](https://github.com/TuongThongHCMUTE/ProjectSE_Nhom16_AppHocNgonNgu/blob/master/document/Group16_TestCaseV1.0.xls)

**Comment by TuongLe18110234** [comment]
[Group16_TestCaseV1.0.xls](https://github.com/TuongThongHCMUTE/ProjectSE_Nhom16_AppHocNgonNgu/files/6447957/Group16_TestCaseV1.0.xls)

**Comment by TuongLe18110234** [comment]
[Group16_TestCaseV1.0.xls](https://github.com/TuongThongHCMUTE/ProjectSE_Nhom16_AppHocNgonNgu/files/6447960/Group16_TestCaseV1.0.xls)
