### ISSUE TITLE
4. Upload test case cho version V2.0

### ISSUE THREAD

**Issue by TuongLe18110234** [TuongThongHCMUTE/ProjectSE_Nhom16_AppHocNgonNgu#33]
[Group16_TestCaseV2.0.xls](https://github.com/TuongThongHCMUTE/ProjectSE_Nhom16_AppHocNgonNgu/blob/master/document/Group16_TestCaseV2.0.xls)

**Comment by ThongDB18110207** [comment]
[Group16_TestCaseV2.0.xls](https://github.com/TuongThongHCMUTE/ProjectSE_Nhom16_AppHocNgonNgu/files/6543836/Group16_TestCaseV2.0.xls)
Update test case 2.0
