### ISSUE TITLE
[GD02] Xác định yêu cầu chức năng

### ISSUE THREAD

**Issue by ThongDB18110207** [TuongThongHCMUTE/ProjectSE_Nhom16_AppHocNgonNgu#6]
Phân tích yêu cầu hệ thống và yêu cầu người dùng

**Comment by TuongLe18110234** [comment]
Đăng kí và đăng nhập tài khoản học viên
Chức năng học thông qua các chủ đề
Chức năng học thông qua video
Chức năng học thông qua tin tức, các bài báo
Chức năng trò chơi giúp ôn tập kiến thức
Chức năng kiểm tra và đánh giá năng lực
Chức năng nhắc nhở giờ học
Chức năng ghi chú bằng flash card
Xếp hạng học viên
Diễn dàng trao đổi
