### ISSUE TITLE
[GD02] Xác địch yêu cầu phi chức năng

### ISSUE THREAD

**Issue by ThongDB18110207** [TuongThongHCMUTE/ProjectSE_Nhom16_AppHocNgonNgu#7]

**Comment by TuongLe18110234** [comment]
-	Giao diện đẹp, dễ sử dụng, thân thiện với mọi đối tượng sử dụng.
-	Dễ dàng tùy chỉnh, thay đổi các module, tích hợp thêm các thành phần khác.
-	Có tính bảo mật cao, không để lộ thông tin người dùng.

**Comment by TuongLe18110234** [comment]
[project-charter-ITPM.docx](https://github.com/ThongDB18110207/ProjectSE_Nhom16_AppHocNgonNgu/files/6196968/project-charter-ITPM.docx)
