### ISSUE TITLE
[GD03] 1. Sử dụng ngôn ngữ có cấu trúc

### ISSUE THREAD

**Issue by TuongLe18110234** [TuongThongHCMUTE/ProjectSE_Nhom16_AppHocNgonNgu#8]

**Comment by ThongDB18110207** [comment]
Tài liệu đặc tả yêu cầu phần mềm - ngôn ngữ tự nhiên có cấu trúc:
https://github.com/TuongThongHCMUTE/ProjectSE_Nhom16_AppHocNgonNgu/blob/master/report/Milestones/%5BGD3%5D-1-structured-natural-language.docx
