### ISSUE TITLE
[GD03] 2. Sử dụng bảng (mô tả action trong cách 1)

### ISSUE THREAD

**Issue by TuongLe18110234** [TuongThongHCMUTE/ProjectSE_Nhom16_AppHocNgonNgu#9]

**Comment by ThongDB18110207** [comment]
Mô tả action trong cách 1
https://github.com/TuongThongHCMUTE/ProjectSE_Nhom16_AppHocNgonNgu/blob/master/report/Milestones/%5BGD3%5D-2-tabular-specification.docx
